name: Deploy Fullstack App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use your desired Node.js version

    - name: Build frontend
      working-directory: ./frontend  # Path to your frontend
      run: |
        npm install
        npm run build

    - name: Build backend
      working-directory: ./backend  # Path to your backend
      run: |
        npm install
        npm run build  # If applicable

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push frontend Docker image
      run: |
        docker build -t my-frontend ./frontend
        docker tag my-frontend:latest <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-frontend:latest
        docker push <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-frontend:latest

    - name: Build and push backend Docker image
      run: |
        docker build -t my-backend ./backend
        docker tag my-backend:latest <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-backend:latest
        docker push <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-backend:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster <your-cluster-name> --service <your-service-name> --force-new-deployment

